### ISSUE TITLE
How to set the vip items as same as the normal items?

### ISSUE THREAD

**Issue by tydaytygx** [SniperOO7/Zombie-Escape-Premium#9]
How to let the normal players use the vip items?

**Comment by tydaytygx** [comment]
Like the frozon nade, where could I find the flag "a", I didn't find the shop config in the files

**Comment by lucvsss** [comment]
> How to let the normal players use the vip items?

U've to edit it from source code, in ze_menus.sp

**Comment by tydaytygx** [comment]
> 
> 
> > How to let the normal players use the vip items?
> 
> U've to edit it from source code, in ze_menus.sp

OK, thanks for your reply!
